import assert from 'assert/strict';
import fs from 'fs';
import { runPercent, percentageActions, exitStats, type Options } from './level-tpsl-engine';
import { replay, type Action } from './poc-indicator-bias-engine';
import type { Candle } from './hype-freerun-canonical-replay';
const M = 60000, start = Date.UTC(2026, 0, 1);
const cs: Candle[] = Array.from({ length: 30 }, (_, i) => ({ ts: start + i * M, endTs: start + (i + 1) * M,
  open: 100, high: 100, low: 100, close: 100, volume: 1, turnover: 100 }));
const o: Options = { start, end: start + 30 * M, delay: 0, hold: 10 * M, fee: .00055, notional: 10000, equity: 32000 };
const long: Action = { id: 'a', at: start + M, side: 1 }, short: Action = { ...long, side: -1 };
assert.equal(percentageActions(cs, [long], 0, 2, 5)[0].target, 102);
assert.equal(percentageActions(cs, [long], 0, 2, 5)[0].stop, 95);
assert.equal(percentageActions(cs, [short], 0, 2, 5)[0].target, 98);
assert.equal(percentageActions(cs, [short], 0, 2, 5)[0].stop, 105);
let run = runPercent(cs, [long], o, 2, 5);
assert.equal(run.trades[0].reason, 'timeout'); assert.equal(run.trades[0].net, -11);
assert.equal(exitStats(run).timeouts, 1);
cs[3].high = 102;
run = runPercent(cs, [long], o, 2, 5); assert.equal(run.trades[0].exitAt, cs[3].ts); assert.equal(run.trades[0].net, 188.89);
assert.equal(run.trades[0].r, 188.89 / 500); assert.equal(exitStats(run).targets, 1);
cs[3].low = 94;
run = runPercent(cs, [long], o, 2, 5); assert.equal(run.trades[0].reason, 'stop'); assert.equal(run.stats.ambiguous, 1);
assert.equal(run.trades[0].net, -510.725);
assert.equal(runPercent(cs, [long], { ...o, targetFirst: true }, 2, 5).trades[0].reason, 'target');
const second = { id: 'b', at: cs[3].ts, side: 1 as const }, third = { id: 'c', at: cs[4].ts, side: 1 as const };
run = runPercent(cs, [long, second, third], o, 2, 5);
assert.deepEqual(run.accepted.map(x => x.id), ['a', 'c']); assert.equal(run.stats.skippedOccupied, 1);
cs[3].open = 93; cs[3].close = 93; cs[3].low = 93;
assert.equal(runPercent(cs, [long], { ...o, targetFirst: true }, 2, 5).trades[0].exitPrice, 93, 'Gap stop before intrabar target');
cs[3] = { ...cs[3], open: 100, low: 98, high: 100, close: 100 };
run = runPercent(cs, [short], o, 2, 5); assert.equal(run.trades[0].reason, 'target'); assert.equal(run.trades[0].net, 189.11);
cs[2] = { ...cs[2], open: 110, high: 110, low: 110, close: 110 };
const delayed = percentageActions(cs, [long], M, 2, 5)[0];
assert.equal(delayed.target, 112.2); assert.equal(delayed.stop, 104.5);
run = runPercent(cs, [long], { ...o, delay: M }, 2, 5);
assert.equal(run.trades[0].entryPrice, 110); assert.equal(run.trades[0].exitPrice, 100, 'Actual gap after delayed fill');
const quiet = cs.map(b => ({ ...b, open: 100, high: 100, low: 100, close: 100 }));
run = runPercent(quiet, [long], { ...o, delay: M }, 2, 5);
assert.equal(run.trades[0].exitAt, long.at + o.hold + 2 * M, 'Inherited entry delay plus timeout action delay');
const carry = { ...o, end: start + 5 * M };
assert(runPercent(quiet, [long], carry, 2, 5).open);
assert.equal(runPercent(quiet, [long], carry, 2, 5).trades.length, 0);
assert.deepEqual(runPercent(quiet, [long], o, 2, 5).monthly, replay(quiet, [long], o).monthly);
const boundary = { id: 'end', at: cs.at(-1)!.ts, side: 1 as const };
assert(runPercent(quiet, [boundary], { ...o, delay: M }, 2, 5).stats.pendingAtEnd);
assert.throws(() => percentageActions(cs, [long], 0, 0, 5));
assert.throws(() => percentageActions(cs, [{ ...long, stop: 99 }], 0, 2, 5));
const c = JSON.parse(fs.readFileSync('research-inputs/level-tpsl-lv02-2026-09-17.json', 'utf8'));
assert.deepEqual(c.tpPct, c.slPct); assert.equal(c.tpPct.length * c.slPct.length * c.entryGroups, 3185);
assert.equal(c.cumulativeStandaloneAfter, c.cumulativeStandaloneBefore + 3185 + 64);
console.log('LV02 tests passed: both directions, fill-anchored2/5 targets, fees, gap/both-hit ordering, intrabar ownership, lag, timeouts, cutoff/pending, unchanged monthly arithmetic and frozen grid.');
