import assert from 'assert/strict';
import {context,validate} from './major-recovery-replay';
import {read} from './major-recovery-atlas';
import {H,M,type Row} from './major-recovery-policy';
const zone={id:'known',lower:99,upper:101,origin:'support' as const,firstKnownAt:0};
const row:Row={at:4*H,barEnd:4*H,healthy:true,close:98,watch:null,spell:{id:'known@4h',zone,armedAt:H,failedAt:4*H,failedRetestAt:null,above:0,lows:[],neckline:null,necklineKnownAt:null}};
validate(read('research-inputs/major-recovery-ms02-2026-09-16.json').definition);
assert(context([row],4*H,0,'accepted_base').blocked);
assert(!context([row],4*H,0,'retest_base').blocked);
assert(!context([row],4*H+M-1,M,'accepted_base').healthy);
assert(context([row],4*H+M,M,'accepted_base').healthy);
assert(!context([row],5*H,0,'accepted_base').healthy);
const retest:Row={...row,at:5*H,barEnd:5*H,spell:{...row.spell!,failedRetestAt:5*H}};
assert(!context([row,retest],5*H-1,0,'retest_base').blocked);
assert(context([row,retest],5*H,0,'retest_base').blocked);
assert(!context([row,retest],5*H+M-1,M,'retest_base').blocked);
assert(context([row,retest],5*H+M,M,'retest_base').blocked);
const release:Row={...row,at:6*H,barEnd:6*H,spell:null};
assert(!context([row,retest,release],6*H,0,'accepted_base').blocked);
assert(!context([row,retest,release],6*H,0,'retest_base').blocked);
assert(context([row,retest,{...release,healthy:false}],6*H,0,'retest_base').blocked);
console.log('major recovery replay tests passed (12 checks plus frozen-card validation)');
