/** Self-contained local viewer. No CDN, credentials, or network dependencies. */
export function renderPocViewer(data: unknown): string {
  const payload = JSON.stringify(data).replace(/</g, '\\u003c');
  return `<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Historical POC / NPOC</title>
<style>
*{box-sizing:border-box}body{margin:0;background:#10151d;color:#dce5ef;font:14px system-ui}main{max-width:1700px;margin:auto;padding:24px}h1{font-size:25px;margin:0 0 8px}.muted{color:#94a9bc}header{margin-bottom:20px}.controls{display:flex;gap:15px;flex-wrap:wrap;align-items:center;background:#1a2431;padding:14px;border-radius:8px}label{display:inline-flex;gap:7px;align-items:center}input,select,button{background:#0e1721;color:#e5efff;border:1px solid #486077;padding:7px;border-radius:4px}input[type=range]{width:100%;padding:0;margin:20px 0}canvas{display:block;width:100%;height:430px;background:#121c28;border:1px solid #324052}#summary{margin:12px 0}#details{padding:15px;background:#1a2431;margin:16px 0;line-height:1.7}#histogram{height:140px}table{width:100%;border-collapse:collapse;font-variant-numeric:tabular-nums}th,td{padding:9px;border-bottom:1px solid #293a4a;text-align:left;white-space:nowrap}th{position:sticky;top:0;background:#1a2431}th button{width:100%;text-align:left;border:0;background:transparent;padding:0}tr{cursor:pointer}tr:hover,tr.selected{background:#23364a}.tablewrap{overflow:auto;max-height:600px}.untested{color:#70dfb0}.tested{color:#9faec0}.uncertain{color:#ffc971}.legend{margin:10px 0;line-height:1.7}.badge{color:#ffc971}a{color:#90cafa}
</style><main><header><h1>Historical POC / naked POC</h1><div class="muted">Executed trade volume · finalized UTC profiles · independent venues · research only</div><p id="coverage"></p><div class="badge">Corrected exchange history, not original arrival timestamps. Publication = period end + 60 seconds. Retest evidence = minute end.</div></header>
<div class="controls"><label>Venue <select id="venue"><option value="bybit">Bybit</option><option value="binance">Binance</option></select></label><label>Profile <select id="period"><option value="all">Daily + weekly + monthly</option><option value="day">Daily</option><option value="week">Weekly (Monday UTC)</option><option value="month">Monthly</option></select></label><label>Row width <select id="width"><option value="0.1">$0.10 primary</option><option value="0.05">$0.05 diagnostic</option><option value="0.2">$0.20 diagnostic</option></select></label><label>As of UTC <input id="asof" type="datetime-local"></label><label>Chart <select id="range"><option value="30">30 days</option><option value="90" selected>90 days</option><option value="180">180 days</option><option value="9999">Full history</option></select></label><label><input id="naked" type="checkbox" checked>Untested only</label><label>Find <input id="search" placeholder="date / price / status"></label></div>
<input id="time" type="range" step="60000"><div id="summary"></div><canvas id="chart"></canvas><div class="legend muted">Blue: hourly close on selected venue. Green: untested POC row. Grey: tested. Amber: uncertainty. Click a register row for its saved volume distribution. No forming-period POCs; missing or incomplete profiles are excluded.</div><div id="details">Select a level in the register.</div><canvas id="histogram"></canvas>
<div class="tablewrap"><table><thead><tr id="headers"></tr></thead><tbody id="rows"></tbody></table></div></main>
<script>const D=${payload};</script><script>
const $=id=>document.getElementById(id),iso=t=>new Date(t).toISOString().replace('T',' ').slice(0,19),num=x=>Number(x).toLocaleString('en-US',{maximumFractionDigits:4});
let at=D.end,selected=null,sortKey='center',direction=-1,rows=[];
const columns=[['start','Profile date UTC'],['center','POC price'],['period','Period'],['availableAt','Known UTC'],['status','State at cursor'],['observedRetestAt','Observed retest UTC'],['sharePct','POC share %'],['volume','Base volume']];
$('headers').innerHTML=columns.map(([k,v])=>'<th data-key="'+k+'"><button data-sort="'+k+'">'+v+'</button></th>').join('');
$('coverage').textContent=D.symbol+' | '+iso(D.start)+' → '+iso(D.end)+' | HL unavailable: requester-paid archive access not enabled.';
$('time').min=D.start;$('time').max=D.end;$('time').value=at;$('asof').min=new Date(D.start).toISOString().slice(0,16);$('asof').max=new Date(D.end).toISOString().slice(0,16);
function project(p){const tested=p.retestKnownAt!==null&&p.retestKnownAt<=at,uncertain=p.uncertainKnownAt!==null&&p.uncertainKnownAt<=at;return {...p,status:tested?'tested':uncertain?'uncertain':'untested',observedRetestAt:tested?p.firstObservedRetestAt:null,firstExact:tested&&!(p.uncertainKnownAt!==null&&p.uncertainKnownAt<=p.retestKnownAt)};}
function setup(id){const c=$(id),ratio=window.devicePixelRatio||1;c.width=c.clientWidth*ratio;c.height=c.clientHeight*ratio;const x=c.getContext('2d');x.scale(ratio,ratio);return [x,c.clientWidth,c.clientHeight];}
function draw(){const [c,w,h]=setup('chart'),focus=rows.find(p=>p.id===selected),from=Math.max(D.start,Math.min(at-Number($('range').value)*86400000,focus?focus.availableAt-86400000:at)),bars=D.candles[$('venue').value].filter(b=>b.end>from&&b.end<=at);
 c.fillStyle='#121c28';c.fillRect(0,0,w,h);if(!bars.length){c.fillStyle='#c5d4df';c.fillText('No complete hourly candles in this window.',20,30);return;}
 let lo=Math.min(...bars.map(b=>b.l)),hi=Math.max(...bars.map(b=>b.h));if(focus){lo=Math.min(lo,Number(focus.lower));hi=Math.max(hi,Number(focus.upper));}const pad=Math.max((hi-lo)*.1,.1);lo-=pad;hi+=pad;const x=t=>65+(t-from)/(at-from||1)*(w-90),y=p=>h-35-(p-lo)/(hi-lo)*(h-60);
 c.font='12px system-ui';for(let i=0;i<=6;i++){const p=lo+(hi-lo)*i/6;c.strokeStyle='#2a3949';c.beginPath();c.moveTo(65,y(p));c.lineTo(w-25,y(p));c.stroke();c.fillStyle='#9db0c5';c.fillText(p.toFixed(2),8,y(p)+4);}
 for(let i=0;i<=4;i++){const t=from+(at-from)*i/4;c.fillText(iso(t).slice(0,10),Math.min(w-95,Math.max(65,x(t)-35)),h-10);}
 c.strokeStyle='#76b9f8';c.lineWidth=1.4;c.beginPath();let previous=null;for(const b of bars){if(previous===null||b.end-previous>3600000)c.moveTo(x(b.end),y(b.c));else c.lineTo(x(b.end),y(b.c));previous=b.end;}c.stroke();
 for(const p of rows){const price=Number(p.center);if(price<lo||price>hi||p.availableAt>at)continue;const end=p.observedRetestAt??at;if(end<from&&p.id!==selected)continue;c.strokeStyle=p.id===selected?'#ffe39b':p.status==='untested'?'#66d6ab':p.status==='uncertain'?'#d9ad69':'#64768a';c.globalAlpha=p.id===selected?1:.65;c.lineWidth=p.id===selected?2:1;c.setLineDash(p.status==='tested'?[3,4]:[]);c.beginPath();c.moveTo(x(Math.max(from,p.availableAt)),y(price));c.lineTo(x(Math.min(at,Math.max(end,p.availableAt))),y(price));c.stroke();if(p.id===selected){c.fillStyle='#ffe39b';c.fillText(p.period+' $'+num(p.center),w-180,y(price)-7);}}c.globalAlpha=1;c.setLineDash([]);
}
function detail(){const p=rows.find(p=>p.id===selected),[c,w,h]=setup('histogram');c.clearRect(0,0,w,h);if(!p){$('details').textContent='Select a level in the register.';return;}
 $('details').textContent=p.venue+' '+p.period+' '+iso(p.start).slice(0,10)+' | row ['+p.lower+', '+p.upper+') | '+p.status+' | '+num(p.pocVolume)+' / '+num(p.volume)+' base volume ('+p.sharePct.toFixed(2)+'%) | '+p.verifiedMinutes+'/'+p.expectedMinutes+' verified minutes'+(p.observedRetestAt?' | observed touch '+iso(p.observedRetestAt)+(p.firstExact?'':' (first exact touch uncertain)'):'')+(p.tiedLower.length>1?' | '+p.tiedLower.length+' tied rows; lowest selected':'');
 const bins=p.distribution,lo=Number(bins[0].lower),hi=Number(bins[bins.length-1].lower)+Number(p.width),max=Math.max(...bins.map(b=>Number(b.volume)));c.font='12px system-ui';for(const b of bins){const x=20+(Number(b.lower)-lo)/(hi-lo)*(w-40),bw=Math.max(1,Number(p.width)/(hi-lo)*(w-40)),height=Number(b.volume)/max*(h-30);c.fillStyle=b.lower===p.lower?'#72dbae':'#426889';c.fillRect(x,h-23-height,bw,height);}c.fillStyle='#cad9e7';c.fillText('$'+num(lo),20,h-5);c.fillText('$'+num(hi),w-90,h-5);
}
function update(){at=Math.min(D.end,Math.max(D.start,at));$('time').value=at;$('asof').value=new Date(at).toISOString().slice(0,16);const needle=$('search').value.toLowerCase();
 rows=D.profiles.filter(p=>p.eligible&&p.availableAt<=at&&p.venue===$('venue').value&&p.width===$('width').value&&($('period').value==='all'||p.period===$('period').value)).map(project).filter(p=>(!$('naked').checked||p.status==='untested')&&(!needle||[iso(p.start),p.center,p.status,p.period].join(' ').toLowerCase().includes(needle)));
 rows.sort((a,b)=>{const av=a[sortKey],bv=b[sortKey];if(av===null)return bv===null?0:1;if(bv===null)return -1;return (['period','status'].includes(sortKey)?String(av).localeCompare(String(bv)):Number(av)-Number(bv))*direction||a.id.localeCompare(b.id);});
 document.querySelectorAll('th').forEach(th=>th.setAttribute('aria-sort',th.dataset.key===sortKey?(direction===1?'ascending':'descending'):'none'));
 $('rows').innerHTML=rows.map(p=>'<tr data-id="'+p.id+'" class="'+(p.id===selected?'selected':'')+'"><td>'+iso(p.start).slice(0,10)+'</td><td>'+num(p.center)+'</td><td>'+p.period+'</td><td>'+iso(p.availableAt)+'</td><td class="'+p.status+'">'+p.status+'</td><td>'+(p.observedRetestAt===null?'—':iso(p.observedRetestAt))+'</td><td>'+p.sharePct.toFixed(2)+'</td><td>'+num(p.volume)+'</td></tr>').join('');
 $('summary').textContent=rows.length+' levels shown at '+iso(at)+' UTC. Full saved catalogue includes quality exclusions; this view shows replay-eligible finalized profiles only.';draw();detail();
}
document.querySelectorAll('[data-sort]').forEach(b=>b.onclick=()=>{if(sortKey===b.dataset.sort)direction*=-1;else{sortKey=b.dataset.sort;direction=sortKey==='center'?-1:1;}update();});
$('rows').onclick=e=>{const r=e.target.closest('tr');if(r){selected=r.dataset.id;update();}};
for(const id of ['venue','period','width','range','naked'])$(id).onchange=update;$('search').oninput=update;$('time').oninput=()=>{at=Number($('time').value);update();};$('asof').onchange=()=>{const t=Date.parse($('asof').value+'Z');if(Number.isFinite(t)){at=t;update();}};window.onresize=()=>{draw();detail();};update();
</script></html>`;
}
