import assert from 'assert/strict';
import {contexts,signals,confirmations,future,summary,H,M} from './rally-pullback-features';
const start=Date.UTC(2025,0,1),bars=Array.from({length:1200*60},(_,i)=>{const p=100+Math.sin(i/1800)*4;return {ts:start+i*M,endTs:start+(i+1)*M,open:p,close:p,high:p+.1,low:p-.1,volume:1,turnover:p};});
const cut=1100*60;const a=contexts(bars.slice(0,cut)),b=contexts(bars.map((c,i)=>i<cut?c:{...c,open:200,close:200,high:210,low:190}));
assert.deepEqual(a,b.filter(x=>x.at<=bars[cut-1].endTs));
const grid=Array.from({length:80},(_,i)=>({at:start+i*4*H,returns:{4:i%2?7:5,12:0,24:0,48:0,72:0}}));
const es=signals(grid,start,Infinity).filter(e=>e.family==='rise4h_6pct');assert(es.length>1);
for(let i=1;i<es.length;i++)assert(es[i].at-es[i-1].at>=72*H);
assert.deepEqual(signals(grid.slice(0,50),start,Infinity),signals(grid,start,Infinity).filter(e=>e.at<=grid[49].at));
const cs=Array.from({length:72*60},(_,i)=>({ts:start+i*M,endTs:start+(i+1)*M,open:100,close:100,high:100,low:100,volume:1,turnover:100}));
cs[1]={...cs[1],high:120,low:99};cs[2]={...cs[2],open:118,close:115,high:118,low:114};
const o=future(cs,start);assert(o.horizons[24].lowPct> -2);assert(o.horizons[24].pullbackPct<=-5);assert.equal(o.horizons[24].firstBarrier,'up2');
const ambiguous=cs.map((c,i)=>i===0?{...c,high:103,low:97}:c);assert.equal(future(ambiguous,start).horizons[4].firstBarrier,'ambiguous');
assert(!future(cs.slice(0,100),start).horizons[4]);assert.equal(future(cs,start+73*H).ready,false);
const poisoned=cs.map((c,i)=>i<24*60?c:{...c,high:999,low:1});assert.deepEqual(future(poisoned,start).horizons[24],o.horizons[24]);
const cm=new Map([[start,{price:100,open:100,high:100}],[start+4*H,{price:110,open:100,high:112}],[start+8*H,{price:107,open:110,high:111}]]);
assert.equal(confirmations({at:start,id:'x'},cm,'first_red_4h')!.delayHours,8);
assert.equal(confirmations({at:start,id:'x'},cm,'first_2pct_giveback')!.delayHours,8);
assert.equal(summary([o],24).drop5,0);assert.equal(summary([o],24).pullback5,1);
console.log('RP01 source-prefix, fixed-crossing, spacing, future-ordering, censoring and confirmation-clock tests passed');
