import assert from "assert/strict";
import { commonMaps } from "./market-proxy-comparison";
import { trajectory, trajectoryClass } from "./recovery-trajectory";
import { constructionDecision, ConstructionController, freshCost } from "./ladder-construction-policy";
import type { ResearchAddDecision } from "./replay-causal-engine";
const H = 3600000;
assert.equal(trajectoryClass([.01, .02, -.01, -.03]).state, "failed_reclaim");
assert.equal(trajectoryClass([-.03, -.02, .01, .005]).state, "recovering");
assert.equal(trajectoryClass([-.01, 0, -.001, -.02]).state, "persistent_weak");
assert.equal(trajectoryClass([.01, .01, -.001, .01]).state, "mixed");
assert.throws(() => trajectoryClass([1, 2]));
const raw: any = {};
for (const [j, s] of ["HYPEUSDT", "BTCUSDT", "SOLUSDT"].entries()) {
  let p = 50; raw[s] = Array.from({ length: 220 }, (_, i) => ({ end: i * H, close: p *= Math.exp(.005 * Math.sin(i * .7 + j) + .002 * Math.cos(i * .13)) }));
}
const at = 205 * H, full = trajectory(commonMaps(raw), at, 0);
assert(full.ready); assert.equal(full.trainingEnd, at - 4 * H);
const prefix = Object.fromEntries(Object.entries(raw).map(([s, rows]: any) => [s, rows.filter((x: any) => x.end <= at)]));
assert.deepEqual(trajectory(commonMaps(prefix as any), at, 0), full);
const poisoned = structuredClone(raw); Object.values(poisoned).forEach((rows: any) => rows.filter((x: any) => x.end > at).forEach((x: any) => x.close *= 100));
assert.deepEqual(trajectory(commonMaps(poisoned), at, 0), full);
const lagged = trajectory(commonMaps(raw), at, 60000); assert.equal(lagged.sourceEnd, at - H); assert(lagged.availableAt <= at);
const gap = structuredClone(raw); gap.SOLUSDT = gap.SOLUSDT.filter((x: any) => x.end !== at - H);
assert.equal(trajectory(commonMaps(gap), at, 0).ready, false);
const cfg = { basePositionUsdt: 800, addScaleFactor: 1.35, priceTriggerPct: .3 };
const inventory = Array.from({ length: 8 }, (_, i) => ({ id: String(i), entryPrice: 100, qty: 8 * 1.35 ** i, notional: 800 * 1.35 ** i }));
const d = { at, index: 123, episode: 1, nextDepth: 9, price: 98, priceDropOk: true } as ResearchAddDecision;
const cap = { id: "cap", family: "budget", capDepth: 8 } as const;
assert(constructionDecision(cap, d, inventory, null, null, cfg).veto);
assert(!constructionDecision(cap, { ...d, price: 99.1 }, inventory, null, null, cfg).veto);
assert(Math.abs(freshCost(8, 800, 1.35) - inventory.reduce((s, x) => s + x.notional, 0)) < 1e-8);
const space = { id: "s", family: "spacing", multiple: 1 } as const;
const f = { healthy: true, endTs: at, availableAt: at, atr14: 3 };
assert(constructionDecision(space, d, inventory, null, f, cfg).veto);
assert(!constructionDecision(space, { ...d, price: 97 }, inventory, null, f, cfg).veto);
assert(constructionDecision(space, d, inventory, null, null, cfg).unknown);
assert(constructionDecision(space, d, inventory, null, { ...f, availableAt: at + 1 }, cfg).unknown);
assert(!constructionDecision(space, { ...d, nextDepth: 7 }, inventory.slice(0, 6), null, null, cfg).veto);
const wait = { id: "w", family: "recycle", mode: "wait60" } as const;
const pull = { id: "p", family: "recycle", mode: "pullback" } as const;
const trim = { at: at - H + 1, price: 98 };
assert(constructionDecision(wait, d, inventory, trim, null, cfg).veto);
assert(!constructionDecision(wait, { ...d, at: at + 1 }, inventory, trim, null, cfg).veto);
assert(constructionDecision(pull, d, inventory, trim, null, cfg).veto);
assert(!constructionDecision(pull, { ...d, price: 97 }, inventory, trim, null, cfg).veto);
assert(!constructionDecision(pull, { ...d, at: trim.at + 4 * H }, inventory, trim, null, cfg).veto);
const ctl = new ConstructionController(pull, cfg, () => null);
ctl.observe({ before: [], after: inventory, event: { kind: "open", fillAt: at, price: 100 } } as any);
ctl.observe({ before: inventory, after: inventory.slice(0, 3), event: { kind: "partial", fillAt: at + 1, price: 101 } } as any);
assert.equal(ctl.trim!.price, 101);
ctl.decide({ ...d, at: at + 2, nextDepth: 4, price: 100.8 }); assert(ctl.trim); // permission does not clear anchor
ctl.observe({ before: inventory.slice(0, 3), after: inventory.slice(0, 4), event: { kind: "open", fillAt: at + 3, price: 100 } } as any);
assert.equal(ctl.trim, null);
ctl.observe({ before: inventory.slice(0, 4), after: [], event: { kind: "close", fillAt: at + 4, price: 102 } } as any);
assert.equal(ctl.trim, null); assert.equal(ctl.inventory.length, 0);
console.log("RR03/L10 tests passed: causal trajectory, gaps, publication lag, thresholds, permission vs fill, partial/full reset");
