import assert from 'assert/strict';
import {candidate,labelPair,stats} from './resistance-tp-buffer';
import {futureLabel,type R} from './resistance-tp-opportunity';
import type {Candle} from './hype-freerun-canonical-replay';
const a:R={index:0,at:60000,episode:1,avg:100,cost:1000,qty:10,price:100.5,shade:101.35,normalTarget:101.4,targetPct:1.4};
assert(Math.abs(candidate(a).price-101.04595)<1e-9);assert(!candidate(a).clipped);
assert.equal(candidate({...a,shade:101.1}).price,101);assert(candidate({...a,shade:101.1}).clipped);
assert(candidate({...a,price:101.1}).alreadyAtIntent);assert(candidate({...a,price:101.04595}).alreadyAtIntent);
assert.throws(()=>candidate({...a,targetPct:.5}));
const cs:Candle[]=Array.from({length:5},(_,i)=>({ts:i*60000,endTs:(i+1)*60000,open:100.5,close:100.5,high:100.6,low:100,volume:1,turnover:100}));
cs[0].high=102;cs[2].high=101.2;cs[2].close=101.1;cs[3].open=100.95;cs[4].high=101.5;
const x:R={endIdx:5,tp:'resting_touch',pendingAtEnd:null,metrics:{episodes:[]}},exact=futureLabel(cs,x,[],[],a),p=labelPair(cs,x,[],[],a,exact);
assert.equal(p.buffered!.hit,2);assert.equal(p.exact.hit,4);assert.equal(p.buffered!.fill,p.candidate.price);
const closed={...x,tp:'close_confirmed'},pc=labelPair(cs,closed,[],[],a,futureLabel(cs,closed,[],[],a));assert.equal(pc.buffered!.fill,100.95);
const now={...a,price:101.2},pn=labelPair(cs,x,[],[],now,exact);assert.equal(pn.buffered,null);assert.equal(pn.intent!.fill,100.5,'next open, not old target or signal close');
const end=labelPair(cs,{...x,endIdx:1},[],[],now,exact);assert(!end.intent!.observed);
const early=labelPair(cs,x,[],[{index:1}],a,futureLabel(cs,x,[],[{index:1}],a));assert.equal(early.buffered!.hit,null);
const poisoned=structuredClone(cs);poisoned[4].high=999;const prefix={...x,endIdx:3};
assert.deepEqual(labelPair(cs,prefix,[],[],a,futureLabel(cs,prefix,[],[],a)),labelPair(poisoned,prefix,[],[],a,futureLabel(poisoned,prefix,[],[],a)));
const outcome={pnl:-50},q={...p,exact:{...p.exact,baselineOutcome:outcome}},s=stats([q,{...q,anchorIndex:1}]);
assert.equal(s.union.ladders,1);assert.equal(s.union.lossDollars,-50);assert.equal(s.unionAnchors,2);
console.log('SRT02 tests passed: capped floor, stale rejection, later-bar contacts, intent marketability, next-open proxy, expiry, prefix and deduplication');
