import assert from 'assert/strict';
import {spaced,eligibleLevel,futureLabel,lifetime,H,M,type R} from './resistance-tp-opportunity';
import type {Candle} from './hype-freerun-canonical-replay';
import type {SRMemoryZoneLevel} from '../src/bot/sr-memory-zones';
const d={normalTpPct:1.4,minimumTpPct:1,minimumSpacedTouches:3,touchSpacingMs:6*H};
assert.deepEqual(spaced([0,1,6,7,12].map(x=>({ts:x*H}))),[0,6*H,12*H]);
assert.equal(spaced([0,1,5,6,11].map(x=>({ts:x*H}))).length,2);
const lv:SRMemoryZoneLevel={price:101.2,confirmTs:0,touches:3,highTouches:2,lowTouches:1,touchData:[0,6,12].map(x=>({ts:x*H,price:101.2,side:'resistance'}))};
assert(eligibleLevel(lv,100,100.5,{pct:1.4,targetPrice:101.4},d));
assert(!eligibleLevel(lv,100,100.5,{pct:.5,targetPrice:100.5},d),'never raise stale TP');
assert(!eligibleLevel({...lv,price:100.9},100,100.5,{pct:1.4,targetPrice:101.4},d),'no floor uplift of a lower zone');
assert(!eligibleLevel({...lv,price:101.4},100,100.5,{pct:1.4,targetPrice:101.4},d));
assert(!eligibleLevel({...lv,touchData:lv.touchData.slice(0,2)},100,100.5,{pct:1.4,targetPrice:101.4},d));
const cs:Candle[]=Array.from({length:5},(_,i)=>({ts:i*M,endTs:(i+1)*M,open:100,close:100,high:100,low:99,volume:1,turnover:100}));
cs[0].high=110;cs[2].high=101.3;cs[3].high=102;cs[3].close=101.25;cs[4].open=100.9;
const a={index:0,episode:1,shade:101.2,normalTarget:101.4,qty:10,cost:1000};
const x:R={endIdx:5,tp:'resting_touch',pendingAtEnd:null,metrics:{episodes:[]}};
let z=futureLabel(cs,x,[],[],a);assert.equal(z.hit,2,'cannot fill inside anchor wick');assert.equal(z.normal,3);assert(z.hitBeforeNormal);assert.equal(z.fill,101.2);
z=futureLabel(cs,{...x,tp:'close_confirmed'},[],[],a);assert.equal(z.hit,3);assert.equal(z.fill,100.9,'closed-price label uses next open');
const decision={episode:1,event:{fillIndex:2,fillAt:cs[2].ts,decisionIndex:1,decisionAt:cs[1].endTs,kind:'open',reason:'add'}};
assert.equal(lifetime(cs,x,[decision],[],a).last,1);assert.equal(futureLabel(cs,x,[decision],[],a).hit,null,'no scanning through changed inventory');
assert.equal(futureLabel(cs,x,[],[{index:1}],a).hit,null,'target re-arm stops frozen label');
const prefix=cs.slice(0,3),px={...x,endIdx:3};assert.equal(futureLabel(prefix,px,[],[],a).hit,2);
assert.equal(futureLabel(cs,px,[],[],a).hit,2,'appending future candles must not change fixed-cutoff labels');
const both=structuredClone(cs);both[2].high=102;assert(futureLabel(both,x,[],[],a).sameBar);
const ending={...x,endIdx:4,tp:'close_confirmed'};assert.equal(futureLabel(cs,ending,[],[],a).fill,null,'unobserved next open censored');
const gap=structuredClone(cs);gap[2].ts+=M;assert.throws(()=>futureLabel(gap,x,[],[],a),/continuous closed minutes/);
console.log('SRT01 tests passed: spacing, floors, stale, next-bar-only, expiry, fill timing and future append');
