import assert from 'assert/strict';
import { warning,buildPolicyTape,adaptActions,M,H } from './sfp-rsi-ema-policy';
import { replay,type Action } from './poc-indicator-bias-engine';
import { auditStructuralReplay } from './structural-replay-audit';
const start=Date.UTC(2026,0,1),cs=Array.from({length:40*1440},(_,i)=>({ts:start+i*M,endTs:start+(i+1)*M,open:100,high:101,low:99,close:100,volume:1,turnover:100}));
assert.equal(warning(51,6.01),true);assert.equal(warning(52,7),false);assert.equal(warning(51,6),false);assert.equal(warning(null,7),null);
const t=start+38*24*H+M,full=buildPolicyTape(cs,M),cut=buildPolicyTape(cs.filter(c=>c.endTs<=t-M),M);
assert.deepEqual(full.at(t),cut.at(t));assert.equal(full.at(t)!.ema,100);assert.equal(full.at(start+24*H)!.warning,null);
const changed=cs.map(c=>c.ts<t-M?c:{...c,open:150,high:151,low:149,close:150,turnover:150});assert.deepEqual(buildPolicyTape(changed,M).at(t),full.at(t));
const s:Action={id:'test',at:start,side:1,stop:95,target:110,expiresAt:start+60*M,failureAt:start+15*M};
const o={start,end:start+2*H,delay:0,hold:H,notional:10000,equity:32000,fee:.00055};
const check=(candles=cs,actions=[s],opts=o)=>{const r=replay(candles,actions,opts);auditStructuralReplay(candles,actions,opts,r);return r;};
let r=check();assert.equal(r.trades[0].exitAt,s.failureAt);assert.equal(r.trades[0].reason,'poc_failure');assert.equal(r.trades[0].net,-11);
r=check(cs,[s],{...o,delay:M});assert.equal(r.trades[0].exitAt,s.failureAt!+M);
const tp=cs.map(c=>({...c}));tp[10].high=111;r=check(tp);assert.equal(r.trades[0].reason,'target');
const sl=cs.map(c=>({...c}));sl[10].low=94;r=check(sl);assert.equal(r.trades[0].reason,'stop');
r=check(cs,[s,{...s,id:'new',at:start+16*M,expiresAt:start+70*M,failureAt:undefined}]);assert.equal(r.trades.length,2);
const tape:any={rows:[{at:start,warning:false},{at:start+15*M,warning:true}],at:()=>({warning:false})};
assert.equal(adaptActions([{...s,failureAt:undefined}],tape,'C_entry_block_and_exit').actions[0].failureAt,start+15*M);
tape.at=()=>({warning:true});assert.equal(adaptActions([s],tape,'B_entry_block').actions.length,0);
const bad=check();bad.trades[0].exitAt+=M;assert.throws(()=>auditStructuralReplay(cs,[s],o,bad));
console.log('SF05 tests passed: thresholds, warmup, closed/future clocks, scheduled exit/latency, native protection priority, ownership and audit');
