import assert from 'assert/strict';
import {facts,classify,inventoryNet,partialNet,H} from './support-flatten-reach-policy';
import {analyze} from './support-flatten-reach-study';
const inv=[{id:'p',entryTime:0,entryPrice:100,qty:10}],spell={zone:{lower:99}};
assert(!facts(inv,97,6*H-1,true).clockOnly);assert(facts(inv,98,6*H,true).clockOnly);
assert(facts(inv,98,12*H-1,true).clockOnly);assert(!facts(inv,98,12*H,true).clockOnly);
assert(facts(inv,98,12*H,false).trendOnly);assert(!facts(inv,98.0001,12*H,false).trendOnly);
assert.equal(facts(inv,99,4*H,false).missing,'age+pnl+trend');
assert.equal(facts(inv,97,14*H,false).missing,'trend');
assert.equal(facts(inv,97,14*H,true).missing,'none');
assert.equal(facts([{...inv[0],entryTime:10*H}],97,14*H,true).age,4,'surviving not episode age');
const f=facts(inv,97,8*H,true);assert(classify(f,true,spell,97,false).clockReach);
assert(!classify(f,false,spell,97,false).clockReach);assert(!classify(f,true,null,97,false).clockReach);
assert(!classify(f,true,spell,99,false).clockReach);assert(!classify(f,true,spell,97,true).clockReach);
assert(classify(f,true,spell,97,true).clockRaw,'existing exit raw reach remains explicit');
assert.equal(partialNet(inv,[],101),inventoryNet(inv,101));
assert(Math.abs(partialNet(inv,[{...inv[0],qty:4}],101)-inventoryNet([{...inv[0],qty:6}],101))<1e-9);
const M=60000,cs=Array.from({length:400},(_,i)=>({ts:i*M,endTs:(i+1)*M,open:98,high:98,low:98,close:98}));
const position={id:'p',entryTime:M,entryPrice:100,qty:10},failure={id:'s',zone:{lower:99},failedAt:0};
const tape=Array.from({length:7},(_,i)=>({at:i*H,barEnd:i*H,healthy:true,close:98,spell:failure}));
const opening={episode:1,event:{fillIndex:1,fillAt:M,decisionIndex:0,decisionAt:M,kind:'open',price:100,reason:'time_add'},before:[],after:[position]};
const s={candles:cs,trendBlocked:cs.map(()=>true)},x={name:'fixture',startIdx:1,endIdx:361,metrics:{episodes:[]},accounting:{monthly:[]}};
let a=analyze(s,x,[opening],tape as any,0),r=a.first.find(z=>z.kind==='clock_reach')!;
assert.equal(r.at,361*M);assert.equal(r.mark,null,'no price beyond this path cutoff');assert.equal(r.outcome,null);
const close={episode:1,event:{fillIndex:361,fillAt:361*M,decisionIndex:360,decisionAt:361*M,kind:'close',price:98,reason:'research_exit:exit_2d_1pct'},before:[position],after:[]};
const finished={...x,endIdx:399,metrics:{episodes:[{entry:new Date(M).toISOString(),close:new Date(361*M).toISOString(),pnl:inventoryNet([position],98)}]}};
a=analyze(s,finished,[opening,close],tape as any,0);assert(a.first.some(z=>z.kind==='clock_raw'));assert(!a.first.some(z=>z.kind==='clock_reach'),'already queued full close has no incremental reach');
const released=tape.map(z=>z.at===6*H?{...z,spell:null}:z);a=analyze(s,x,[opening],released as any,0);assert(!a.first.length,'confirmed release suppresses candidate');
console.log('SRF01 tests passed: thresholds, surviving age, source release, strict bound, existing exit overlap, next-open cutoff censoring and fees');
